### ISSUE TITLE
doWork-проблема с потоками

### ISSUE THREAD

**Issue by oblako17** [DikBSD/SharpFBTools#1]
Во время отладки в Visual Studio в Дубликаторе (и в Корректоре тоже), в начале работы с книгами "Поиск копий" и заполнении таблицы застревает, с ошибкой:

// поиск одинаковых fb2-файлов
		private void bw_DoWork( object sender, DoWorkEventArgs e )
		_dtStart = DateTime.Now;
			cbGroupCountForList.SelectedIndex	= _tscbGroupCountForList.SelectedIndex;
			
-		$exception	{"Недопустимая операция в нескольких потоках: попытка доступа к элементу управления '' не из того потока, в котором он был создан."}	System.InvalidOperationException
System.InvalidOperationException
  HResult=0x80131509
  Сообщение = Недопустимая операция в нескольких потоках: попытка доступа к элементу управления '' не из того потока, в котором он был создан.
  Источник = System.Windows.Forms
  Трассировка стека:
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.ComboBox.get_SelectedIndex()
   at Core.Duplicator.CompareForm.bw_DoWork(Object sender, DoWorkEventArgs e) in D:\Progect_VS\SharpFBTools-4.41-src\Source\Core\Duplicator\CompareForm.cs:line 411
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
![dowork](https://user-images.githubusercontent.com/45688702/49813535-afac2f00-fd78-11e8-8c9b-0032e1b19a4f.jpg)

**Comment by DikBSD** [comment]
Надо переписывать весь GUI для развязки потоков. Как будет время - займусь.
